### PR TITLE
TreeInfo can use alternative Pango classifications

### PR DESCRIPTION
**Pull request by hyanwong**
To match Ana's new lineage imputation metadata keys.

Relevant to #134 as it raises an error if the metadata key isn't present.

Instead of saving both designations in the TreeInfo class, you have to pick one at the start. I thought that would reduce the amount of output from the various tabulating functions, and I think we probably want to pick just one classification or the other, not use both. But happy for this to change, obviously.

### CODE REVIEW

**Comment by hyanwong** [comment]
Not that not all samples have a GISAID pango classification, so I have put "unknown" for these (I thought I might as well use lowercase, to distinguish from the imputed "Unknown").

**Review by jeromekelleher — COMMENTED** [review]
Classification is a very generic term, maybe pango_lineage_source or something?

**Comment by hyanwong** [comment]
Good point. Will change.

**Comment by hyanwong** [comment]
Perhaps just "pango_source" would do?

**Comment by jeromekelleher** [comment]
Sure

**Comment by hyanwong** [comment]
Done

**Pull request merged**
