### PR TITLE
Lineage imputation and sample subgraph plots

### PR DESCRIPTION
**Pull request by a-ignatieva**
Code for imputing the Pango lineage of nodes in an inferred tree sequence. This uses a a 2-step procedure of (1) copying the parent’s or a child’s lineage whenever possible (if the connecting edge doesn’t have any lineage-defining mutations on it), and (2) imputing the lineage of a node based on that of its parent + the lineage-defining mutations on the connecting edge. These steps are run iteratively over the ts until everything has a lineage assigned. WIP, and I need to add some tests here.

Also function in utils for visualising the history of a given sample node (tracing up through the ARG until other sample nodes are reached, showing any recombinations on the way).

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks great, thanks @a-ignatieva!

A few minor things:
- The consensus_mutations.json is 8.5 MB which is too big really for storing in a git repo like this. Maybe we could just add a comment in the code saying where to download the file, and provide the path as an argument to the imputation function?
- Can you run [black](https://pypi.org/project/black/) on the code please? (Black is the best thing that's happened to me in years, it saves soooo much time and energy not having to think about code layout!)

Other than that I think we can merge and iterate - although I guess we'll have to rebase and squash the commits in order to get rid of hte big JSON file completely from the history.

**Comment by jeromekelleher** [comment]
This [guide](https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#rebasing) for squashing might come in handy

**Comment by a-ignatieva** [comment]
Sorted I think.

**Comment by jeromekelleher** [comment]
Merged, thanks @a-ignatieva!

**Pull request merged**
