### PR TITLE
Rerooting

### PR DESCRIPTION
**Pull request by jeromekelleher**
Adds a rerooting operation for tskit trees, and does some code reorganisation.

@hyanwong can you have a look at the rerooting tests here to make sure I've implemented the right operation? Look for TestRerooting in the test_tree_ops.py module.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
The operation that I've implemented is very simple, but it's quite possible I've gotten the wrong end of the stick here and implemented the wrong thing. Some eyes on the examples would be very helpful.

**Comment by szhan** [comment]
Similarly, for `test_ternary_example_n6_leaf`, node 3 is connected to only node 7, not node 9. So, I think the output tree should look like:

```
# 3.00┊       3   ┊
#     ┊       ┃   ┊
#     ┊       7   ┊
#     ┊    ┏━━┻━┓ ┊
# 2.00┊    9    ┃ ┊
#     ┊  ┏━┻━┓  ┃ ┊
# 1.00┊  6   8  ┃ ┊
#     ┊ ┏┻┓ ┏┻┓ ┃ ┊
# 0.00┊ 0 1 4 5 2 ┊
#     0           1
```

**Comment by szhan** [comment]
A trivial test, but could add this.

```python
def test_example_same_root(self):
    #  1.00┊  2  ┊
    #      ┊ ┏┻┓ ┊
    #  0.00┊ 0 1 ┊
    #      0     1
    # ->
    #  1.00┊  2  ┊
    #      ┊ ┏┻┓ ┊
    #  0.00┊ 0 1 ┊
    #      0     1
    ts1 = tskit.Tree.generate_balanced(2, arity=2).tree_sequence
    ts2 = sc2ts.reroot(ts1, new_root=2)
    self.check_properties(before=ts1, after=ts2, root=2)
    tree = ts2.first()
    nt.assert_array_equal(tree.parent_array, ts1.parent_array)
    nt.assert_array_equal(ts2.nodes_time, ts1.nodes_time)
```

**Comment by hyanwong** [comment]
I don't understand how your algorithm works @jeromekelleher. Could you possibly explain it? Don'r we simply want to traverse through the tree-as-a-graph from a given node? I find thinking about this as an oriented tree pretty hard compared to a simple graph.

**Comment by jeromekelleher** [comment]
> By the way, why aren't we keeping the sample node times as they were in the original TS. This should be possible with the sc2ts samples.

There's no original tree here in the actual inference problem, it's just a star tree describing the data and times get set later on.

**Comment by jeromekelleher** [comment]
Thanks for the input here, let me digest

**Comment by jeromekelleher** [comment]
Ah yes, you're right. Thanks, will fix!

**Comment by hyanwong** [comment]
The recursive version is quite easy to code up (and IMO easier to understand), if you need to have something to test against. I'm happy to code that up, if only for the test suite.

**Comment by hyanwong** [comment]
> > By the way, why aren't we keeping the sample node times as they were in the original TS. This should be possible with the sc2ts samples.
> 
> There's no original tree here in the actual inference problem, it's just a star tree describing the data and times get set later on.

You mean ultrametric, not star, I think? I assume we have internal topology. We do know the time of the root node (which is older than the other samples) though.

**Comment by jeromekelleher** [comment]
No it's a star.

**Comment by jeromekelleher** [comment]
Leave it with me, thanks.

**Comment by hyanwong** [comment]
> No it's a star.

Oh, you mean from the matching process (i.e. it doesn't create internal nodes), not from e.g. the NJ tree inference?

**Comment by hyanwong** [comment]
Re tests, it's probably worth trying with a very deeply branched tree, e.g.

```python
tree = tskit.Tree.generate_balanced(15)
# re-root on node 2, setting its time to e.g. 5. This requires reversing the parent-child relationship for 4 edges, I think.
```

**Comment by jeromekelleher** [comment]
> Oh, you mean from the matching process (i.e. it doesn't create internal nodes), not from e.g. the NJ tree inference?

No, this is the *input* to the NJ inference. We just package up the data for a sample group as a tree sequence in a star topology, with all the mutations on the sample branches. It's just a straightforward way of keeping the datamodel straight.

**Comment by jeromekelleher** [comment]
OK, thanks very much for the input here @szhan and @hyanwong, that was super helpful. I'm pretty set on using oriented tree algorithms here as it's super simple once you get it straight. It's just reversing the parent child relationships on all nodes on the path to the (old) root.

**Comment by hyanwong** [comment]
> OK, thanks very much for the input here @szhan and @hyanwong, that was super helpful. I'm pretty set on using oriented tree algorithms here as it's super simple once you get it straight. It's just reversing the parent child relationships on all nodes on the path to the (old) root.

Yep, that should be enough. Possibly worth also testing on trees with polytomies (although I don't think NJ normally gives those). E.g. reroot `tskit.Tree.generate_balanced(15, arity=4)` on node 14. I think the same logic should apply.

It should also be the same for trees with unary nodes above the root, right? It could be that some implementations of NJ produce these (i.e. placing a sample as the root node, rather than placing a root in the middle of an edge, which would become unary on re-rooting):

**Comment by jeromekelleher** [comment]
Ok, great, this seems to be working. Including rerooting in the inference is really easy with these tools and all the existing tests pass. I'm going to merge this and run with UPGMA for a bit and see how we get on. Swapping in NJ afterwards should be simple.

**Comment by jeromekelleher** [comment]
> Yep, that should be enough. Possibly worth also testing on trees with polytomies (although I don't think NJ normally gives those). E.g. reroot tskit.Tree.generate_balanced(15, arity=4) on node 14. I think the same logic should apply.

Ternary example in their already

**Comment by hyanwong** [comment]
This is a valid unrooted NJ tree, right (dunno if any programs output this, though). Could re-root on e.g. node 2.

```python
ts = tskit.Tree.generate_comb(4).tree_sequence.simplify([1, 2, 3, 6])
ts.draw_svg()
```
Screenshot 2024-09-27 at 15 51 17

**Pull request merged**
