### PR TITLE
Switch in biotite NJ algorithm for local tree building

### PR DESCRIPTION
**Pull request by hyanwong**
For testing. I think this works, but I'm getting test suite errors elsewhere, so can't be certain. Can you try it @jeromekelleher . You'll need to `pip install biotite`.

### CODE REVIEW

**Comment by hyanwong** [comment]
Hmm, it's not working because the samples aren't the first in the tree sequence. I suppose we want to keep the sample IDs in the old and new trees the same, do we?

**Comment by hyanwong** [comment]
OK, I think I fixed my bugs (sorry). At the moment the tests are failing, but I suspect this is because they are hardcoded to UPGMA results? Does that sound plausible? Here are the failing tests:

```
FAILED tests/test_inference.py::TestRealData::test_2020_02_02 - AssertionError
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-02] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-03] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-04] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-05] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-06] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-07] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-08] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-09] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-10] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-11] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_date_validate[2020-02-13] - ValueError: Data mismatch
FAILED tests/test_inference.py::TestRealData::test_group[0c36395a702379413ffc855f847873c6-2020-01-24-1-strains2] - assert 0 == 1
FAILED tests/test_inference.py::TestRealData::test_group[9d00e2a016661caea4c2d9abf83375b8-2020-01-30-1-strains3] - AssertionError: assert ['SRR12162235...'SRR12162232'] == ['SRR12162232...'SRR12162235']
FAILED tests/test_inference.py::TestRealData::test_group[2f508c7ba05387dec0adbf2db4a7481a-2020-02-04-1-strains4] - assert 0 == 1
FAILED tests/test_inference.py::TestSyntheticAlignments::test_recombinant_example_1 - AssertionError: assert {'mutations':...ght': 29904}]} == {'mutations':...ght': 29904}]}
FAILED tests/test_inference.py::TestMatchingDetails::test_match_recombinant - assert [35, 50] == [36, 51]
FAILED tests/test_inference.py::TestMatchRecombinants::test_example_1 - assert [35, 50] == [36, 51]
```

**Comment by jeromekelleher** [comment]
There's various bits and pieces broken. I'll fix it up and see what we have, leave it with me.

**Comment by jeromekelleher** [comment]
While this works for reinferring the existing groups, it doesn't have the properties we need at inference time. I'm having to rewire quite a bit of it, particularly in terms of node times.

I don't really follow the algorithm, and I think it'll help to break it up into two phases: convert the biotite tree into tskit, and then reroot the tskit tree.

Can you sketch out the rerooting algorithm in tskit please? Assume the last sample is the real root, and that times are arbitrary.

**Comment by jeromekelleher** [comment]
I've made major changes here - I don't really want to deal with the merge mess, so will just force push over the last commit, if that's OK.

I'll take it from here. If you can give me a sketch of the tskit rerooting algorithm I'll code it up. I'll probably push a version in which we just use biotite first without the rerooting though.

**Comment by hyanwong** [comment]
Sure, feel free to force push.

The re-rooting algorithm is basically the same for tskit as for biotite. We define a function that returns all the "links" attached to a node, regardless of whether they are parents or children. We then traverse through the internal nodes by pushing them onto a stack. Here's an (untested) re-phrasing of the previous code:

```python
def attached_nodes(tree, u):
    # all nodes attached to this node, regardless of whether
    # parents or children
    children = tree.children(u) or tuple()
    if tree.parent(u) == tskit.NULL:
        return children
    return children + (tree.parent(u), )

def reroot(ts, start):
    assert ts.num_trees == 1
    tree = ts.first()
    tables = ts.dump_tables()
    tables.edges.clear()
    tables.nodes.clear()
    tables.sites.clear()
    tables.mutations.clear()
    
    L = tables.sequence_length
    curr_id = tables.nodes.add_row(time=time)  # don't treat the local tree root as a sample
    stack = [(start, None, curr_id, ts.node(start).time)]
    node_map = {}
    while len(stack) > 0:
        node, prev_node, curr_id, time = stack.pop()
        for new_node in attached_nodes(tree, node):
            if new_node != prev_node:
                if tree.is_leaf(new_node):
                    ts_node = ts.node(new_node)
                    new_time = ts_node.time
                    if time <= new_time:
                        raise ValueError(
                            f"Child leaf {sample_indexes[new_node.index]} has time {new_time} but parent {curr_id} is at time {time}")
                    u = tables.nodes.append(ts_node)
                else:
                    new_time = time - epsilon
                    u = tables.nodes.add_row(time=new_time)
                assert new_time < tables.nodes[curr_id].time
                tables.edges.add_row(parent=curr_id, child=u, left=0, right=L)
                if tree.is_leaf(new_node):
                    node_map[new_node] = u
                    # print("added internal", u, f"at time {time} (parent is {parent})")
                else:
                    stack.append((new_node, node, u, new_time))
                    # print("made leaf", u, f"(was {sample_indexes[new_node.index]}) at time {time} (parent is {parent})")
    # Make sure that the nodes in the new TS map to those in the old
    tables.sort()
    tables.simplify([node_map[u] for u in np.arange(ts.num_samples)])
    new_ts = tables.tree_sequence()

    # Now add mutations, and compute_mutation_parents
```

**Comment by hyanwong** [comment]
If you get a nice, generalised version of a re-rooting algorithm working, we should post it in the tskit GH discussions, potentially with a view to incorporating it into either tskit and/or phylokit, as this is a basic phylogenetic operation.

**Comment by hyanwong** [comment]
(NB: I just through: it could simply be that I've set the root node at the same time as the attachment point. If so you can just decrement the root node time by an epsilon, and it should fit into the tree just fine.

**Comment by jeromekelleher** [comment]
In the interest of changing one thing at a time I've switched over to using UPGMA from biotite without the rerooting. This should give us essentially identical results. I'll run it overnight to see how we fare in terms of robustness.

**Comment by jeromekelleher** [comment]
(I'll follow up tomorrow with updates aiming to support UPGMA and NJ as options, possibly also supporting rerooting as an option too, but I think that sounds like something that should always be done, regardless)

**Comment by jeromekelleher** [comment]
I can this overnight and we get almost identical results to the previous implementation as of 2020-12-01. There's a tiny difference in the overall number of mutations (left new, right old)
```
mutations                                94672                                                                         │mutations                                94668
recurrent                                  955                                                                         │recurrent                                  960
reversions                                 904                                                                         │reversions                                 909
immediate_reversions                       113                                                                         │immediate_reversions                       121
```

**Pull request merged**
